### ISSUE TITLE
Adafruit ST7789 library with alternate 1 HW SPI

### ISSUE THREAD

**Issue by wa2mze** [MCUdude/MegaCoreX#131]
I tried to build the graphicstest example using the hw spi option.  I want to add the SPI.swap(1) call to use the first alternate pin options, but the SPI.swap(1);  I added after the call to the constructor does not compile.

_exit status 1
'SPI' does not name a type

I assume that this is because inside the library the spi class is given a different name, but I couldn't find this in the library sources.  I think adafruit has subclassed the arduino spi class for their own use, I would then have to call their class to call the swap() method, but it may be a private class object.  Has anybody gotten the adafruit graphics libraries to work with MegaCoreX?

**Comment by MCUdude** [comment]
I'm closing this issue because this is something that needs to be fixed in the Adafruit library repo

**Comment by SpenceKonde** [comment]
Ugh fucking adafruit and rewrapping libraries....

@wa2mze how does this behave on DxCore? I made some changes specifically for that library, but if the swap methods are being vanished by the Adafruit library.... well.... lets jus say I'm gonna be pissed. My other question is whether you are includin SPI in the main sketch, because if you don't do that, it ain't never gonna work and those error messages would be entirely expected.
