### ISSUE TITLE
Problems of understanding the Serial Pinout

### ISSUE THREAD

**Issue by mikrocoder** [MCUdude/MegaCoreX#80]
Hello,

my problem is solved. I was confused by your pinout to the Nano Everys. Because there are no default pins for the Serial am Every. I don't know how you count the pins yet.
Serial pin 25, 24
Serial1 pin 34, 35
Serial2 pin 24, 23

and why the pin 24 appears twice?

Apparently you give the Arduino digital pin numbering and then again some sort of counting method that has nothing to do with the controller housing pins.

Am Every has only these possibilities with your package.
Counting mode is the Arduino numbering.

Serial.swap(0); // default USB
Serial.swap(1); // swapped USB to Pin Tx D9, Rx D10
Serial1.swap(0); // default Pin Tx D1, Rx D0
Serial2.swap(1); // swapped to Pin Tx D2, Rx D7

All other possibilities of enumeration only confuse, I mean, because you can't use them at Every.

Please do not misunderstand. I don't want to upset you. I want to make sure that you read the documentation more clearly, because I like the controller and your package.

**Comment by MCUdude** [comment]
Sorry for being so slow to reply. For some reason, I haven't been notified.

It took me a while to understand what you meant, but by going through the Nano Every pin definition file I found the issue you're pointing out. It as to do with some copy/paste errors from the Uno Wifi pinout. I will push a fix soon. Thanks for reporting!

I will rearrange Serial2 a little:
Available pin combinations for the *Nano Every* pinout are:

| Peripheral | Default                            | Alternative                  |
|------------|------------------------------------|------------------------------|
| Serial     | swap(0)  **or**  pins(25,24)       | swap(1)  **or**  pins(9,10)  |
| Serial1    | swap(0)  **or**  pins(1,0)         | swap(1)  **or**  pins(34,35) |
| Serial2    | swap(0)  **or**  pins(2,7)         | swap(1)  **or**  pins(28,27) |

**Comment by mikrocoder** [comment]
Hello,

no do not close yet. Thanks for reading and understanding. For longer texts I use DeepL. But unfortunately you have once again thrown the pin numbers coloured. Is it possible that you mixed the Arduino Every numbering with the standard 48 IC pinout? Because a Nano Every definitely does not have a pin 34 and 35. Is there a reason why you do not want to use the Arduino numbering as suggested? It would be unique on the Every. I haven't checked Uno Wifi Rev.2 yet.  :-)  :-)

**Comment by MCUdude** [comment]
If you look in the **Alternative pins** section in the README, you'll see an updated table:

Available pin combinations for the *Nano Every* pinout are:

| Peripheral | Default                                                          | Alternative                                   |
|------------|------------------------------------------------------------------|-----------------------------------------------|
| Serial     | swap(0)  **or**  pins(25,24) <br/>(connected to USB-serial chip) | swap(1)  **or**  pins(9,10)                   |
| Serial1    | swap(0)  **or**  pins(1,0)                                       | swap(1)  **or**  pins(34,35) (not broken out) |
| Serial2    | swap(0)  **or**  pins(2,7)                                       | swap(1)  **or**  pins(28,27) (not broken out) |
| Serial3    | swap(0)  **or**  pins(6,3)                                       | swap(1)  **or**  pins(37,38) (not broken out) |

Note that no matter how I re-orient the Arduino pins, swap for Serial1 will never be available, since the pins aren't broken out on the Nano Every.

The official Nano Every implementation does not even support pin swapping.

**Comment by mikrocoder** [comment]
Hello,

oh, yes. I'm confused now myself. I'm sorry. Too many pinouts.   :-)
